# Site settings
title: UNIS-UN
email: contact@unis-un.org
description: "unis-un does stuff"

#Upcoming Confrence year (Remeber to use quotes)
conf_year: "2015"

#Social media
twitter_username: unis_un
facebook_username: unis-un

# Build settings
markdown: kramdown
permalink: pretty
